branches:
  - master

plugins:
  - "@semantic-release/exec"
  - "@semantic-release/changelog"
  - "@semantic-release/git"
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"

prepare:
  - path: "@semantic-release/exec"
    cmd: "cat mix.exs"

  - path: "@semantic-release/exec"
    cmd: "sed -i -e 's/version: \"0.0.0\"\/version: \"${nextRelease.version}\"\/g' mix.exs"

publish:
  - "@semantic-release/github"

  - path: "@semantic-release/exec"
    cmd: "mix hex.publish package --yes"